import { NextResponse } from "next/server";

/**
 * Module discovery endpoint for the Clinical Mission Control dashboard.
 *
 * Returns metadata for every module exposed by the OOREP local repertory,
 * including name, description, benefit #, and which output keys it produces.
 * The frontend uses this to populate the module picker and know what data
 * each panel can render.
 */

export type PortalModule = {
  id: string;
  name: string;
  category:
    | "differential"
    | "navigation"
    | "analytics"
    | "safety"
    | "materia_medica"
    | "teaching"
    | "workflow"
    | "infrastructure"
    | "statistics";
  benefit: number | string;
  description: string;
  route: string; // API sub-path for execution
  inputs: string[];
  outputs: string[];
  defaultEnabled: boolean;
};

const MODULES: PortalModule[] = [
  {
    id: "repertorize",
    name: "Repertorization",
    category: "differential",
    benefit: 1,
    description: "Multi-symptom classical grade-based remedy ranking",
    route: "/api/admin/repertorize",
    inputs: ["symptoms"],
    outputs: ["results", "cycle_analysis"],
    defaultEnabled: true,
  },
  {
    id: "cycles",
    name: "Cycles \u0026 Segments",
    category: "differential",
    benefit: 59,
    description:
      "Herscu method: structural case-to-cycle matching with segment coverage thresholds",
    route: "/api/admin/cycles",
    inputs: ["symptoms"],
    outputs: ["cycle_analysis", "segment_matches", "segment_coverage"],
    defaultEnabled: true,
  },
  {
    id: "remedy_comparator",
    name: "Remedy Comparator",
    category: "differential",
    benefit: 3,
    description: "Multi-remedy overlap, divergence, and Jaccard analysis",
    route: "/api/admin/compare",
    inputs: ["remedies"],
    outputs: ["overlap", "exclusive", "jaccard"],
    defaultEnabled: false,
  },
  {
    id: "srp_detector",
    name: "SRP Detector",
    category: "differential",
    benefit: 13,
    description: "Strange-Rare-Peculiar keyword detection with weighted scoring",
    route: "/api/admin/srp",
    inputs: ["case_rubrics"],
    outputs: ["flags", "severity", "boost_multiplier"],
    defaultEnabled: true,
  },
  {
    id: "phantom_rubric",
    name: "Phantom Rubric Analyzer",
    category: "differential",
    benefit: 27,
    description: "Gini + entropy flags for low-differentiation rubrics",
    route: "/api/admin/phantoms",
    inputs: ["rubric_ids"],
    outputs: ["phantoms", "gini", "entropy"],
    defaultEnabled: true,
  },
  {
    id: "rubric_cooccurrence",
    name: "Rubric Co-occurrence",
    category: "differential",
    benefit: 24,
    description: "Mine remedy pairs, polycrest clusters, association rules",
    route: "/api/admin/cooccurrence",
    inputs: ["remedy"],
    outputs: ["pairs", "clusters"],
    defaultEnabled: false,
  },
  {
    id: "elimination",
    name: "Elimination Analyzer",
    category: "differential",
    benefit: 15,
    description: 'Exclusion logic: "what symptom rules out X?"',
    route: "/api/admin/elimination",
    inputs: ["symptoms", "remedy"],
    outputs: ["excluded_by", "coverage"],
    defaultEnabled: false,
  },
  {
    id: "potency_guidance",
    name: "Potency Guidance",
    category: "differential",
    benefit: 16,
    description: "Classical potency ladder + remedy-specific profiles",
    route: "/api/admin/potency",
    inputs: ["remedy", "case_context"],
    outputs: ["potency_suggestion", "ladder"],
    defaultEnabled: true,
  },
  {
    id: "acute_chronic",
    name: "Acute / Chronic Layer",
    category: "differential",
    benefit: 17,
    description: "Tag acute vs chronic symptoms and layer-separate repertorization",
    route: "/api/admin/layers",
    inputs: ["symptoms"],
    outputs: ["acute", "chronic", "layer_scores"],
    defaultEnabled: true,
  },
  {
    id: "rubric_explorer",
    name: "Rubric Explorer",
    category: "navigation",
    benefit: 2,
    description: "Kent hierarchy parent/child navigation, sibling traversal",
    route: "/api/admin/rubric-explore",
    inputs: ["rubric_id"],
    outputs: ["parents", "children", "siblings"],
    defaultEnabled: false,
  },
  {
    id: "private_rubrics",
    name: "Private Rubric Manager",
    category: "navigation",
    benefit: 41,
    description: "Practitioner-created custom rubrics with merge-to-repertorization",
    route: "/api/admin/private-rubrics",
    inputs: ["rubric_text", "remedy_grades"],
    outputs: ["private_rubric_id"],
    defaultEnabled: false,
  },
  {
    id: "patient_cases",
    name: "Patient Case Manager",
    category: "analytics",
    benefit: "7–11",
    description: 'Hermes Q&A: "What did I prescribe Mrs. J. last month?"',
    route: "/api/admin/cases",
    inputs: ["patient_id"],
    outputs: ["timeline", "summary", "pattern"],
    defaultEnabled: true,
  },
  {
    id: "cohort_analytics",
    name: "Patient Cohort Analytics",
    category: "analytics",
    benefit: 26,
    description: "Outcome rates, remedy timelines, symptom-success correlation",
    route: "/api/admin/cohort",
    inputs: ["remedy"],
    outputs: ["outcomes", "top_followups", "success_correlation"],
    defaultEnabled: false,
  },
  {
    id: "family_constellation",
    name: "Family Constellation",
    category: "analytics",
    benefit: 10,
    description: "Family remedy patterns, cross-generational linking",
    route: "/api/admin/family",
    inputs: ["patient_id"],
    outputs: ["pattern"],
    defaultEnabled: false,
  },
  {
    id: "suppression_tracker",
    name: "Suppression Tracker",
    category: "analytics",
    benefit: 11,
    description: "Suppression history alerts and miasm-tracking tags",
    route: "/api/admin/suppression",
    inputs: ["patient_id"],
    outputs: ["suppressions", "warnings"],
    defaultEnabled: true,
  },
  {
    id: "approval_gate",
    name: "Practitioner Approval Gate",
    category: "safety",
    benefit: 50,
    description: "prescriber_ack safety gate (strict/audit/test modes)",
    route: "/api/admin/approve",
    inputs: ["recommendation"],
    outputs: ["status", "audit_log_id"],
    defaultEnabled: true,
  },
  {
    id: "red_flags",
    name: "Red Flag Detector",
    category: "safety",
    benefit: 51,
    description: "Critical/urgent/advisory symptom detection with referral triggers",
    route: "/api/admin/red-flags",
    inputs: ["symptoms"],
    outputs: ["status", "flags", "referral_recommended"],
    defaultEnabled: true,
  },
  {
    id: "phi_scrubber",
    name: "PHI Scrubber",
    category: "safety",
    benefit: 49,
    description: "Automated PHI detection + reversible pseudonym mapping",
    route: "/api/admin/phi-scrub",
    inputs: ["text"],
    outputs: ["scrubbed", "pseudonyms"],
    defaultEnabled: true,
  },
  {
    id: "audit_trail",
    name: "Audit Trail",
    category: "safety",
    benefit: "32, 53",
    description: "SHA-256 hash chain, immutable prescription logs, licensure export",
    route: "/api/admin/audit",
    inputs: ["record"],
    outputs: ["log_id", "integrity"],
    defaultEnabled: true,
  },
  {
    id: "remedy_relationships",
    name: "Remedy Relationships",
    category: "materia_medica",
    benefit: "4, 19–21",
    description: "Complementary, antidotal, inimical, antidote classical tables",
    route: "/api/admin/relationships",
    inputs: ["remedy"],
    outputs: ["complementary", "antidotes", "inimical"],
    defaultEnabled: true,
  },
  {
    id: "kent_vs_boenn",
    name: "Kent vs Boenninghausen",
    category: "materia_medica",
    benefit: 46,
    description: "Both methods side-by-side, divergence analysis, auto-recommendation",
    route: "/api/admin/kent-vs-boen",
    inputs: ["rubrics"],
    outputs: ["kent", "boenninghausen", "recommendation"],
    defaultEnabled: false,
  },
  {
    id: "personality_bridge",
    name: "Personality Engine Bridge",
    category: "materia_medica",
    benefit: "47, 56",
    description: "Link 50-remedy personality system to OOREP remedy IDs",
    route: "/api/admin/personality",
    inputs: ["remedy"],
    outputs: ["personality_profile"],
    defaultEnabled: false,
  },
  {
    id: "student_training",
    name: "Student Training",
    category: "teaching",
    benefit: 38,
    description: "Simulated patients, 4-option quizzes, progress tracking",
    route: "/api/admin/training",
    inputs: ["mode"],
    outputs: ["simulated_case", "quiz"],
    defaultEnabled: false,
  },
  {
    id: "vignette_quiz",
    name: "Clinical Vignette Quiz",
    category: "teaching",
    benefit: 45,
    description: "Real outcome records → difficulty-tiered teaching quizzes",
    route: "/api/admin/vignette-quiz",
    inputs: ["topic"],
    outputs: ["quiz"],
    defaultEnabled: false,
  },
  {
    id: "grand_rounds",
    name: "Grand Rounds",
    category: "teaching",
    benefit: 48,
    description: "Multi-case synthesis, common themes, markdown teaching narratives",
    route: "/api/admin/grand-rounds",
    inputs: ["patient_ids"],
    outputs: ["narrative", "themes"],
    defaultEnabled: false,
  },
  {
    id: "soap_assembler",
    name: "SOAP Assembler",
    category: "workflow",
    benefit: 31,
    description: "Template-based SOAP generation from case notes",
    route: "/api/admin/soap",
    inputs: ["case_notes"],
    outputs: ["soap"],
    defaultEnabled: false,
  },
  {
    id: "letter_generator",
    name: "Letter Generator",
    category: "workflow",
    benefit: 34,
    description: "Referral / summary / prescription letters with homeopathic rationale",
    route: "/api/admin/letter",
    inputs: ["case_id", "letter_type"],
    outputs: ["letter_md"],
    defaultEnabled: false,
  },
  {
    id: "freshness_tracker",
    name: "Remedy Freshness Tracker",
    category: "workflow",
    benefit: 39,
    description: "Staleness alerts, review queue, proven-source tracking",
    route: "/api/admin/freshness",
    inputs: ["remedy"],
    outputs: ["staleness_score", "review_queue"],
    defaultEnabled: false,
  },
  {
    id: "rubric_gap",
    name: "Rubric Gap Analyzer",
    category: "workflow",
    benefit: 40,
    description: "Coverage gap detection, rubric quality scoring, new-rubric suggestions",
    route: "/api/admin/rubric-gaps",
    inputs: ["symptoms"],
    outputs: ["gaps", "quality_scores"],
    defaultEnabled: false,
  },
  {
    id: "subagent_orchestrator",
    name: "Subagent Orchestrator",
    category: "infrastructure",
    benefit: "35–37",
    description: "Case analysis plans, literature review delegation, second-opinion routing",
    route: "/api/admin/orchestrate",
    inputs: ["task"],
    outputs: ["plan"],
    defaultEnabled: false,
  },
  {
    id: "model_router",
    name: "Model Router",
    category: "infrastructure",
    benefit: 57,
    description: "Local/cloud task routing, performance tracking, fallback chains",
    route: "/api/admin/model-route",
    inputs: ["task"],
    outputs: ["route"],
    defaultEnabled: false,
  },
  {
    id: "materia_medica",
    name: "Materia Medica",
    category: "materia_medica",
    benefit: "18, 21",
    description: "Full-text proving DB for classical materia medica lookup",
    route: "/api/admin/materia-medica",
    inputs: ["remedy"],
    outputs: ["proving_text", "sources"],
    defaultEnabled: false,
  },
  {
    id: "kingdom_taxonomy",
    name: "Kingdom Taxonomy",
    category: "materia_medica",
    benefit: 22,
    description: "Mineral/Plant/Animal tags with family cross-references",
    route: "/api/admin/kingdom",
    inputs: ["remedy"],
    outputs: ["kingdom", "family", "source"],
    defaultEnabled: false,
  },
  {
    id: "botanical_bridge",
    name: "Botanical Bridge",
    category: "materia_medica",
    benefit: 28,
    description: "WHO Monograph cross-map for botanical remedies",
    route: "/api/admin/botanical",
    inputs: ["remedy"],
    outputs: ["monograph", "safety_flags"],
    defaultEnabled: false,
  },
  {
    id: "genomic_hypothesis",
    name: "Genomic Hypothesis",
    category: "materia_medica",
    benefit: 29,
    description: "SNP → remedy outcome correlation hypotheses",
    route: "/api/admin/genomic",
    inputs: ["snp_list"],
    outputs: ["hypotheses", "confidence"],
    defaultEnabled: false,
  },
  {
    id: "flashcard_srs",
    name: "Flashcard SRS",
    category: "teaching",
    benefit: 44,
    description: "SM-2 spaced repetition for materia medica study",
    route: "/api/admin/srs",
    inputs: ["remedy", "user_id"],
    outputs: ["due_cards", "stats"],
    defaultEnabled: false,
  },
  {
    id: "cron_tasks",
    name: "Cron Tasks",
    category: "infrastructure",
    benefit: "33, 42, 43",
    description: "Follow-up alerts, vector auto-rebuild, GitHub backup",
    route: "/api/admin/cron",
    inputs: ["task_name"],
    outputs: ["status"],
    defaultEnabled: false,
  },
  // ── Statistical Modules (v3.6) ─────────────────────────────
  {
    id: "outcome_predictor_stats",
    name: "Outcome Predictor Stats",
    category: "statistics",
    benefit: 64,
    description: "ROC/AUC validation, calibration analysis, bootstrap CI on predictions",
    route: "/api/admin/outcome-stats",
    inputs: ["predictor", "positive_outcomes"],
    outputs: ["roc", "calibration", "bootstrap_ci"],
    defaultEnabled: false,
  },
  {
    id: "remedy_network_analysis",
    name: "Remedy Network Analysis",
    category: "statistics",
    benefit: 65,
    description: "Graph centrality, community detection, PageRank on remedy relationships",
    route: "/api/admin/network",
    inputs: ["remedy"],
    outputs: ["centrality", "communities", "shortest_path"],
    defaultEnabled: false,
  },
  {
    id: "outcome_comparator",
    name: "Outcome Comparator",
    category: "statistics",
    benefit: 66,
    description: "Mann-Whitney U, odds ratio, Cohen's d, Cliff's delta between remedies",
    route: "/api/admin/compare-outcomes",
    inputs: ["remedy_a", "remedy_b"],
    outputs: ["mann_whitney", "odds_ratio", "cohens_d", "cliffs_delta"],
    defaultEnabled: false,
  },
  {
    id: "repertory_pca",
    name: "Repertory PCA",
    category: "statistics",
    benefit: 67,
    description: "SVD/PCA on remedy-rubric matrix with 2D/3D projections",
    route: "/api/admin/pca",
    inputs: ["n_components"],
    outputs: ["components", "explained_variance", "projection_2d", "projection_3d"],
    defaultEnabled: false,
  },
  {
    id: "case_complexity",
    name: "Case Complexity Scorer",
    category: "statistics",
    benefit: 68,
    description: "Symptom entropy, coverage gaps, redundancy, composite complexity score",
    route: "/api/admin/complexity",
    inputs: ["symptoms", "rubric_matches"],
    outputs: ["complexity_score", "components"],
    defaultEnabled: false,
  },
  {
    id: "inter_rater_reliability",
    name: "Inter-Rater Reliability",
    category: "statistics",
    benefit: 69,
    description: "Cohen's kappa, Fleiss' kappa, ICC for practitioner agreement",
    route: "/api/admin/irr",
    inputs: ["ratings"],
    outputs: ["kappa", "icc", "interpretation"],
    defaultEnabled: false,
  },
  {
    id: "meta_analysis",
    name: "Meta-Analysis Engine",
    category: "statistics",
    benefit: 70,
    description: "Fixed/random-effects meta-analysis with heterogeneity metrics",
    route: "/api/admin/meta",
    inputs: ["studies"],
    outputs: ["pooled_proportion", "heterogeneity", "forest_plot"],
    defaultEnabled: false,
  },
  {
    id: "power_analysis",
    name: "Power Analysis",
    category: "statistics",
    benefit: 71,
    description: "Sample size, power curves, minimum detectable effect calculations",
    route: "/api/admin/power",
    inputs: ["baseline_rate", "expected_rate", "alpha", "power"],
    outputs: ["sample_size", "power_curve", "mde"],
    defaultEnabled: false,
  },
  {
    id: "survival_analysis",
    name: "Survival Analysis",
    category: "statistics",
    benefit: 72,
    description: "Kaplan-Meier curves and hazard ratios for time-to-improvement",
    route: "/api/admin/survival",
    inputs: ["remedy"],
    outputs: ["km_curve", "median_survival", "hazard_ratio"],
    defaultEnabled: false,
  },
  {
    id: "resampling_engine",
    name: "Resampling Engine",
    category: "statistics",
    benefit: 73,
    description: "Bootstrap CI, permutation tests, k-fold cross-validation",
    route: "/api/admin/resample",
    inputs: ["data", "statistic", "n_iterations"],
    outputs: ["ci", "p_value", "fold_scores"],
    defaultEnabled: false,
  },
  // ── Feature Expansion Modules (v3.7) ──
  {
    id: "reverse_repertorization",
    name: "Reverse Repertorization",
    category: "differential",
    benefit: 74,
    description: "Given a remedy, show all rubrics where it appears graded",
    route: "/api/admin/reverse_repertorization",
    inputs: ["remedy"],
    outputs: ["rubrics", "by_chapter"],
    defaultEnabled: true,
  },
  {
    id: "constitutional_tracker",
    name: "Constitutional Remedy Tracker",
    category: "workflow",
    benefit: 75,
    description: "Longitudinal constitutional prescription history with potency escalation",
    route: "/api/admin/constitutional_tracker",
    inputs: ["case_id"],
    outputs: ["constitutional_remedy", "escalation", "max_potency"],
    defaultEnabled: true,
  },
  {
    id: "duplicate_remedy_detector",
    name: "Duplicate Remedy Detector",
    category: "safety",
    benefit: 76,
    description: "Antidote and inimical prescription warnings",
    route: "/api/admin/duplicate_detector",
    inputs: ["case_id", "proposed_remedy"],
    outputs: ["safe", "warnings", "interactions"],
    defaultEnabled: true,
  },
  {
    id: "posology_scheduler",
    name: "Posology Scheduler",
    category: "workflow",
    benefit: 77,
    description: "Classical dosing and repetition guidance",
    route: "/api/admin/posology",
    inputs: ["case_type", "previous_potency", "outcome"],
    outputs: ["recommended_potency", "repetition", "assess_after"],
    defaultEnabled: true,
  },
  {
    id: "symptom_severity",
    name: "Symptom Severity Scorer",
    category: "analytics",
    benefit: 78,
    description: "Intensity-based repertorization weighting (1-10 scale)",
    route: "/api/admin/severity",
    inputs: ["case_id", "rubric_id", "severity"],
    outputs: ["weighted_scores", "severity_summary"],
    defaultEnabled: true,
  },
  {
    id: "clinical_tips",
    name: "Clinical Tips Engine",
    category: "materia_medica",
    benefit: 79,
    description: "Practitioner notes and author commentary on rubrics",
    route: "/api/admin/clinical_tips",
    inputs: ["rubric_id", "tip", "reliability"],
    outputs: ["total_tips", "by_reliability"],
    defaultEnabled: false,
  },
  {
    id: "batch_protocols",
    name: "Batch Protocol Builder",
    category: "workflow",
    benefit: 80,
    description: "Standard protocols for common conditions",
    route: "/api/admin/protocols",
    inputs: ["condition", "symptoms"],
    outputs: ["protocols", "steps"],
    defaultEnabled: false,
  },
  {
    id: "inventory",
    name: "Inventory Manager",
    category: "workflow",
    benefit: 81,
    description: "Remedy stock and expiry tracking",
    route: "/api/admin/inventory",
    inputs: ["remedy", "potency", "quantity"],
    outputs: ["total_items", "low_stock_count", "expiring_soon"],
    defaultEnabled: false,
  },
  {
    id: "miasm_timeline",
    name: "Miasm Timeline",
    category: "differential",
    benefit: 82,
    description: "Miasmatic layer history visualization",
    route: "/api/admin/miasm_timeline",
    inputs: ["case_id"],
    outputs: ["active_layers", "deepest_layer", "layer_transitions"],
    defaultEnabled: false,
  },
  {
    id: "case_similarity",
    name: "Case Similarity Search",
    category: "analytics",
    benefit: 83,
    description: "Find previous cases with similar symptom patterns",
    route: "/api/admin/case_similarity",
    inputs: ["symptoms", "outcome_filter"],
    outputs: ["similar_cases", "what_worked", "practice_stats"],
    defaultEnabled: false,
  },
  {
    id: "author_filter",
    name: "Author Filter",
    category: "materia_medica",
    benefit: 84,
    description: "Filter repertory by provenance authority",
    route: "/api/admin/author_filter",
    inputs: ["author", "exclude"],
    outputs: ["filtered_rubrics", "n_excluded"],
    defaultEnabled: false,
  },
  {
    id: "quick_lookup",
    name: "Quick Symptom Lookup",
    category: "navigation",
    benefit: 85,
    description: "Single-symptom fast search without full repertorization",
    route: "/api/admin/quick_lookup",
    inputs: ["query"],
    outputs: ["results"],
    defaultEnabled: true,
  },
  {
    id: "prescription_pdf",
    name: "Prescription PDF Generator",
    category: "workflow",
    benefit: 86,
    description: "Professional prescription document creation",
    route: "/api/admin/prescription_pdf",
    inputs: ["remedy", "potency", "dosage"],
    outputs: ["html", "pdf_path"],
    defaultEnabled: false,
  },
  {
    id: "appointment_scheduler",
    name: "Appointment Scheduler",
    category: "workflow",
    benefit: 87,
    description: "Follow-up and acute appointment calendar",
    route: "/api/admin/appointments",
    inputs: ["case_id", "appointment_date", "type"],
    outputs: ["next_appointment", "overdue_count"],
    defaultEnabled: false,
  },
  {
    id: "followup_prompts",
    name: "Follow-Up Prompts",
    category: "workflow",
    benefit: 88,
    description: "Automated follow-up questions based on prescription",
    route: "/api/admin/followup",
    inputs: ["remedy", "potency", "days_since"],
    outputs: ["questions", "recommended_timing"],
    defaultEnabled: false,
  },
  {
    id: "case_summarizer",
    name: "Case Summarizer",
    category: "workflow",
    benefit: 89,
    description: "Auto-generate readable case summaries from structured data",
    route: "/api/admin/summarize",
    inputs: ["case_data"],
    outputs: ["summary", "narrative"],
    defaultEnabled: false,
  },
  {
    id: "rubric_quality",
    name: "Rubric Quality Scorer",
    category: "analytics",
    benefit: 90,
    description: "Score rubric quality by distribution and diversity",
    route: "/api/admin/rubric_quality",
    inputs: ["rubric_id"],
    outputs: ["quality_score", "metrics"],
    defaultEnabled: false,
  },
  {
    id: "narrative_extractor",
    name: "Symptom Narrative Extractor",
    category: "analytics",
    benefit: 91,
    description: "NLP extraction of symptoms from free text",
    route: "/api/admin/narrative_extract",
    inputs: ["narrative"],
    outputs: ["extracted_symptoms", "suggested_rubrics"],
    defaultEnabled: false,
  },
  {
    id: "cross_reference",
    name: "Cross-Reference Repertory",
    category: "materia_medica",
    benefit: 92,
    description: "Universal rubric concordance across repertory systems",
    route: "/api/admin/cross_reference",
    inputs: ["rubric_id", "target_system"],
    outputs: ["equivalents", "coverage"],
    defaultEnabled: false,
  },
  {
    id: "proving_text_search",
    name: "Proving Text Search",
    category: "materia_medica",
    benefit: 93,
    description: "Full-text search inside materia medica proving texts",
    route: "/api/admin/proving_search",
    inputs: ["query", "remedy", "author"],
    outputs: ["results", "n_matches"],
    defaultEnabled: false,
  },
  {
    id: "repertory_synthesis",
    name: "Repertory Synthesis",
    category: "materia_medica",
    benefit: 94,
    description: "Build custom repertories from multiple sources",
    route: "/api/admin/synthesis",
    inputs: ["source_repertories", "rubric_selections"],
    outputs: ["custom_repertory", "n_rubrics"],
    defaultEnabled: false,
  },
  {
    id: "polarity_analysis",
    name: "Polarity Analysis",
    category: "differential",
    benefit: 95,
    description: "Heiner Frei's systematic symptom confirmation method",
    route: "/api/admin/polarity",
    inputs: ["symptoms", "candidate_remedies"],
    outputs: ["ranked_remedies", "net_scores"],
    defaultEnabled: false,
  },
  {
    id: "voice_to_text",
    name: "Voice-to-Text Audio Import",
    category: "workflow",
    benefit: 96,
    description: "Audio import and transcription for any microphone",
    route: "/api/admin/voice_import",
    inputs: ["audio_path"],
    outputs: ["transcript", "extracted_symptoms"],
    defaultEnabled: false,
  },
  {
    id: "patient_portal",
    name: "Patient Portal",
    category: "infrastructure",
    benefit: 97,
    description: "Read-only patient access to case summaries",
    route: "/api/admin/patient_portal",
    inputs: ["case_id"],
    outputs: ["summary", "prescription_history"],
    defaultEnabled: false,
  },
  {
    id: "billing",
    name: "Billing Integration",
    category: "infrastructure",
    benefit: 98,
    description: "Invoice and insurance claim tracking",
    route: "/api/admin/billing",
    inputs: ["case_id", "services"],
    outputs: ["invoice", "total", "insurance_code"],
    defaultEnabled: false,
  },
  {
    id: "export_research",
    name: "Export Research Formats",
    category: "analytics",
    benefit: 99,
    description: "CSV, JSON, and research format exports",
    route: "/api/admin/export",
    inputs: ["case_data", "format"],
    outputs: ["file_path", "rows"],
    defaultEnabled: false,
  },
  {
    id: "global_stats",
    name: "Global Stats Dashboard",
    category: "analytics",
    benefit: 100,
    description: "Practice-wide analytics overview",
    route: "/api/admin/stats",
    inputs: [],
    outputs: ["top_remedies", "outcome_rates", "case_types"],
    defaultEnabled: false,
  },
  // ── Advanced Statistical & ML Modules (v3.8) ──────────────
  {
    id: "thompson_sampling",
    name: "Thompson Sampling Remedies",
    category: "statistics",
    benefit: 111,
    description: "Bayesian beta-distribution remedy ranking with exploration/exploitation balance",
    route: "/api/admin/thompson",
    inputs: ["remedy", "trials", "successes"],
    outputs: ["thompson_scores", "posterior_params"],
    defaultEnabled: false,
  },
  {
    id: "rubric_bandit",
    name: "Multi-Armed Bandit Rubric Selection",
    category: "statistics",
    benefit: 112,
    description: "UCB/Thompson rubric selection that optimizes questioning strategy",
    route: "/api/admin/bandit",
    inputs: ["symptoms", "available_rubrics"],
    outputs: ["selected_rubrics", "cumulative_reward"],
    defaultEnabled: false,
  },
  {
    id: "propensity_scored",
    name: "Propensity-Scored Outcomes",
    category: "statistics",
    benefit: 113,
    description: "Propensity score matching for outcome prediction with confounders",
    route: "/api/admin/propensity",
    inputs: ["remedy", "case_features"],
    outputs: ["matched_outcomes", "propensity_scores"],
    defaultEnabled: false,
  },
  {
    id: "rubric_discrimination",
    name: "Rubric Discrimination Indices",
    category: "statistics",
    benefit: 114,
    description: "Gini and KL divergence to identify maximally discriminating rubrics",
    route: "/api/admin/rubric_discrim",
    inputs: ["rubric_id"],
    outputs: ["gini", "kl_divergence", "discrimination_score"],
    defaultEnabled: false,
  },
  {
    id: "hierarchical_bayesian",
    name: "Hierarchical Bayesian Similarity",
    category: "statistics",
    benefit: 115,
    description: "Multi-level Bayesian model for remedy similarity across kingdoms",
    route: "/api/admin/hierarchical_bayes",
    inputs: ["remedy", "kingdom"],
    outputs: ["similar_remedies", "posterior_distributions"],
    defaultEnabled: false,
  },
  {
    id: "cv_weight_learning",
    name: "CV Symptom Weight Learning",
    category: "statistics",
    benefit: 116,
    description: "Cross-validated optimization of symptom weights for repertorization",
    route: "/api/admin/cv_weights",
    inputs: ["training_cases"],
    outputs: ["optimal_weights", "cv_scores"],
    defaultEnabled: false,
  },
  {
    id: "sprt",
    name: "Sequential Remedy Testing (SPRT)",
    category: "statistics",
    benefit: 117,
    description: "Wald sequential probability ratio test for early remedy confirmation",
    route: "/api/admin/sprt",
    inputs: ["remedy", "sequential_observations"],
    outputs: ["decision", "likelihood_ratio", "boundary_check"],
    defaultEnabled: false,
  },
  {
    id: "gaussian_process",
    name: "Gaussian Process Surrogate",
    category: "statistics",
    benefit: 118,
    description: "GP surrogate model for expensive repertorization queries",
    route: "/api/admin/gp_surrogate",
    inputs: ["symptom_space"],
    outputs: ["posterior_mean", "posterior_variance", "acquisition_scores"],
    defaultEnabled: false,
  },
  {
    id: "causal_remedy_effects",
    name: "Causal Remedy Effects",
    category: "statistics",
    benefit: 119,
    description: "Do-calculus and instrumental variables for causal remedy attribution",
    route: "/api/admin/causal_effects",
    inputs: ["remedy", "outcome", "confounders"],
    outputs: ["ate", "confidence_intervals", "dag"],
    defaultEnabled: false,
  },
  {
    id: "ensemble_stacking",
    name: "Ensemble Retrieval with Stacking",
    category: "statistics",
    benefit: 120,
    description: "Stack multiple retrieval methods with learned meta-weights",
    route: "/api/admin/ensemble_stack",
    inputs: ["symptoms"],
    outputs: ["stacked_scores", "base_learner_outputs"],
    defaultEnabled: false,
  },
  {
    id: "discriminant_rubric",
    name: "Discriminant Rubric Selector",
    category: "differential",
    benefit: 121,
    description: "Fisher discriminant analysis to find maximally differentiating rubrics",
    route: "/api/admin/discriminant",
    inputs: ["candidate_remedies"],
    outputs: ["discriminant_rubrics", "separation_scores"],
    defaultEnabled: false,
  },
  {
    id: "information_theoretic",
    name: "Information-Theoretic Case Workup",
    category: "statistics",
    benefit: 122,
    description: "Mutual information and entropy-guided symptom selection",
    route: "/api/admin/info_theoretic",
    inputs: ["symptoms"],
    outputs: ["information_gains", "entropy_profile"],
    defaultEnabled: false,
  },
  {
    id: "adaptive_symptom_sequencer",
    name: "Adaptive Symptom Sequencer",
    category: "workflow",
    benefit: 123,
    description: "Reinforcement learning to optimize symptom elicitation order",
    route: "/api/admin/adaptive_seq",
    inputs: ["partial_symptoms"],
    outputs: ["next_question", "expected_info_gain"],
    defaultEnabled: false,
  },
  {
    id: "latent_embedding",
    name: "Latent Symptom Embedding",
    category: "statistics",
    benefit: 124,
    description: "Learned low-dimensional symptom space for visual clustering",
    route: "/api/admin/latent_embed",
    inputs: ["symptoms"],
    outputs: ["embeddings", "clusters"],
    defaultEnabled: false,
  },
  {
    id: "confusion_matrix",
    name: "Confusion Matrix Differential",
    category: "differential",
    benefit: 125,
    description: "Remedy confusion matrix for systematic differential diagnosis",
    route: "/api/admin/confusion_matrix",
    inputs: ["candidate_remedies"],
    outputs: ["confusion_pairs", "differentiating_rubrics"],
    defaultEnabled: false,
  },
  {
    id: "knn_proven",
    name: "K-Nearest Proven Cases",
    category: "analytics",
    benefit: 126,
    description: "KNN search over proven case database for similar remedy outcomes",
    route: "/api/admin/knn_cases",
    inputs: ["symptoms", "k"],
    outputs: ["nearest_cases", "distances"],
    defaultEnabled: false,
  },
  {
    id: "bayesian_network",
    name: "Bayesian Rubric Network",
    category: "statistics",
    benefit: 127,
    description: "DAG-structured Bayesian network for rubric-remedy dependency modeling",
    route: "/api/admin/bayes_net",
    inputs: ["symptoms"],
    outputs: ["posterior_probabilities", "dag_structure"],
    defaultEnabled: false,
  },
  {
    id: "symptom_cooccurrence",
    name: "Symptom Co-occurrence Lift",
    category: "analytics",
    benefit: 128,
    description: "Lift and chi-square analysis of symptom co-occurrence patterns",
    route: "/api/admin/cooccurrence_lift",
    inputs: ["symptoms"],
    outputs: ["lift_pairs", "chi_square_scores"],
    defaultEnabled: false,
  },
  {
    id: "active_learning_intake",
    name: "Active Learning Intake Tracker",
    category: "workflow",
    benefit: 129,
    description: "Active learning to identify which intake questions most reduce uncertainty",
    route: "/api/admin/active_learning",
    inputs: ["partial_intake"],
    outputs: ["query_strategy", "uncertainty_reduction"],
    defaultEnabled: false,
  },
  {
    id: "remedy_calibration",
    name: "Remedy Confidence Calibration",
    category: "statistics",
    benefit: 130,
    description: "Platt scaling and isotonic regression for remedy confidence calibration",
    route: "/api/admin/calibration",
    inputs: ["raw_scores", "outcomes"],
    outputs: ["calibrated_scores", "reliability_curve"],
    defaultEnabled: false,
  },
  // ── Intake & Case Structure Modules (v3.8) ────────────────
  {
    id: "patient_intake",
    name: "Patient Intake Engine",
    category: "workflow",
    benefit: 131,
    description: "9-phase structured patient interview with optimal-next-question guidance",
    route: "/api/admin/intake_engine",
    inputs: ["case_data"],
    outputs: ["phase_status", "next_question", "coverage"],
    defaultEnabled: false,
  },
  {
    id: "question_bank",
    name: "Interview Question Bank",
    category: "workflow",
    benefit: 132,
    description: "Curated question bank organized by interview phase and symptom category",
    route: "/api/admin/question_bank",
    inputs: ["phase"],
    outputs: ["questions", "suggested_rubrics"],
    defaultEnabled: false,
  },
  {
    id: "chief_complaint",
    name: "Chief Complaint Triager",
    category: "workflow",
    benefit: 133,
    description: "Structured chief complaint extraction with severity and duration tagging",
    route: "/api/admin/chief_complaint",
    inputs: ["case_text"],
    outputs: ["complaint", "severity", "duration"],
    defaultEnabled: false,
  },
  {
    id: "concomitant",
    name: "Concomitant Detector",
    category: "differential",
    benefit: 134,
    description: "Identify concomitant symptoms that modify the primary complaint picture",
    route: "/api/admin/concomitant",
    inputs: ["symptoms"],
    outputs: ["concomitants", "associations"],
    defaultEnabled: false,
  },
  {
    id: "modality_extractor",
    name: "Modality Extractor",
    category: "differential",
    benefit: 135,
    description: "Parse and structure modality tags (better/worse, time, temperature, etc.)",
    route: "/api/admin/modality_extract",
    inputs: ["case_text"],
    outputs: ["modalities", "qualified_symptoms"],
    defaultEnabled: false,
  },
  {
    id: "causation_timeline",
    name: "Causation & Timeline",
    category: "analytics",
    benefit: 136,
    description: "Extract etiology and temporal progression from case narrative",
    route: "/api/admin/causation",
    inputs: ["case_text"],
    outputs: ["etiology", "timeline_events", "onset"],
    defaultEnabled: false,
  },
  {
    id: "mental_emotional",
    name: "Mental/Emotional Prober",
    category: "workflow",
    benefit: 137,
    description: "Structured mental-emotional symptom extraction and sentiment analysis",
    route: "/api/admin/mental_emotional",
    inputs: ["case_text"],
    outputs: ["me_symptoms", "sentiment", "intensity"],
    defaultEnabled: false,
  },
  {
    id: "generals_survey",
    name: "Generals Survey",
    category: "workflow",
    benefit: 138,
    description: "General symptom survey: thermal, food, sleep, energy patterns",
    route: "/api/admin/generals",
    inputs: ["case_text"],
    outputs: ["generals", "thermal_response", "food_cravings"],
    defaultEnabled: false,
  },
  {
    id: "constitutional_snapshot",
    name: "Constitutional Snapshot",
    category: "analytics",
    benefit: 139,
    description: "Constitutional type extraction from body/mind/genitals characteristics",
    route: "/api/admin/constitutional",
    inputs: ["case_data"],
    outputs: ["constitution", "build", "diathesis"],
    defaultEnabled: false,
  },
  {
    id: "intake_analyzer",
    name: "Intake Analyzer",
    category: "analytics",
    benefit: 140,
    description: "Aggregate intake quality scoring with completeness and coverage metrics",
    route: "/api/admin/intake_analyzer",
    inputs: ["intake_data"],
    outputs: ["quality_score", "coverage", "gaps"],
    defaultEnabled: false,
  },
  {
    id: "case_analysis_bridge",
    name: "Case Analysis Bridge",
    category: "differential",
    benefit: 141,
    description: "Cross-reference confusion matrix and co-occurrence lift for integrated analysis",
    route: "/api/admin/case_bridge",
    inputs: ["confusion_matrix", "cooccurrence"],
    outputs: ["bridge_analysis", "integrated_scores"],
    defaultEnabled: false,
  },
];

export async function GET(_request: Request) {
  return NextResponse.json({ ok: true, modules: MODULES });
}
