import { NextResponse } from "next/server";

/**
 * Module discovery endpoint for the Clinical Mission Control dashboard.
 *
 * Returns metadata for every module exposed by the OOREP local repertory,
 * including name, description, benefit #, and which output keys it produces.
 * The frontend uses this to populate the module picker and know what data
 * each panel can render.
 */

export type PortalModule = {
  id: string;
  name: string;
  category:
    | "differential"
    | "navigation"
    | "analytics"
    | "safety"
    | "materia_medica"
    | "teaching"
    | "workflow"
    | "infrastructure";
  benefit: number | string;
  description: string;
  route: string; // API sub-path for execution
  inputs: string[];
  outputs: string[];
  defaultEnabled: boolean;
};

const MODULES: PortalModule[] = [
  {
    id: "repertorize",
    name: "Repertorization",
    category: "differential",
    benefit: 1,
    description: "Multi-symptom classical grade-based remedy ranking",
    route: "/api/admin/repertorize",
    inputs: ["symptoms"],
    outputs: ["results", "cycle_analysis"],
    defaultEnabled: true,
  },
  {
    id: "cycles",
    name: "Cycles \u0026 Segments",
    category: "differential",
    benefit: 59,
    description:
      "Herscu method: structural case-to-cycle matching with segment coverage thresholds",
    route: "/api/admin/cycles",
    inputs: ["symptoms"],
    outputs: ["cycle_analysis", "segment_matches", "segment_coverage"],
    defaultEnabled: true,
  },
  {
    id: "remedy_comparator",
    name: "Remedy Comparator",
    category: "differential",
    benefit: 3,
    description: "Multi-remedy overlap, divergence, and Jaccard analysis",
    route: "/api/admin/compare",
    inputs: ["remedies"],
    outputs: ["overlap", "exclusive", "jaccard"],
    defaultEnabled: false,
  },
  {
    id: "srp_detector",
    name: "SRP Detector",
    category: "differential",
    benefit: 13,
    description: "Strange-Rare-Peculiar keyword detection with weighted scoring",
    route: "/api/admin/srp",
    inputs: ["case_rubrics"],
    outputs: ["flags", "severity", "boost_multiplier"],
    defaultEnabled: true,
  },
  {
    id: "phantom_rubric",
    name: "Phantom Rubric Analyzer",
    category: "differential",
    benefit: 27,
    description: "Gini + entropy flags for low-differentiation rubrics",
    route: "/api/admin/phantoms",
    inputs: ["rubric_ids"],
    outputs: ["phantoms", "gini", "entropy"],
    defaultEnabled: true,
  },
  {
    id: "rubric_cooccurrence",
    name: "Rubric Co-occurrence",
    category: "differential",
    benefit: 24,
    description: "Mine remedy pairs, polycrest clusters, association rules",
    route: "/api/admin/cooccurrence",
    inputs: ["remedy"],
    outputs: ["pairs", "clusters"],
    defaultEnabled: false,
  },
  {
    id: "elimination",
    name: "Elimination Analyzer",
    category: "differential",
    benefit: 15,
    description: 'Exclusion logic: "what symptom rules out X?"',
    route: "/api/admin/elimination",
    inputs: ["symptoms", "remedy"],
    outputs: ["excluded_by", "coverage"],
    defaultEnabled: false,
  },
  {
    id: "potency_guidance",
    name: "Potency Guidance",
    category: "differential",
    benefit: 16,
    description: "Classical potency ladder + remedy-specific profiles",
    route: "/api/admin/potency",
    inputs: ["remedy", "case_context"],
    outputs: ["potency_suggestion", "ladder"],
    defaultEnabled: true,
  },
  {
    id: "acute_chronic",
    name: "Acute / Chronic Layer",
    category: "differential",
    benefit: 17,
    description: "Tag acute vs chronic symptoms and layer-separate repertorization",
    route: "/api/admin/layers",
    inputs: ["symptoms"],
    outputs: ["acute", "chronic", "layer_scores"],
    defaultEnabled: true,
  },
  {
    id: "rubric_explorer",
    name: "Rubric Explorer",
    category: "navigation",
    benefit: 2,
    description: "Kent hierarchy parent/child navigation, sibling traversal",
    route: "/api/admin/rubric-explore",
    inputs: ["rubric_id"],
    outputs: ["parents", "children", "siblings"],
    defaultEnabled: false,
  },
  {
    id: "private_rubrics",
    name: "Private Rubric Manager",
    category: "navigation",
    benefit: 41,
    description: "Practitioner-created custom rubrics with merge-to-repertorization",
    route: "/api/admin/private-rubrics",
    inputs: ["rubric_text", "remedy_grades"],
    outputs: ["private_rubric_id"],
    defaultEnabled: false,
  },
  {
    id: "patient_cases",
    name: "Patient Case Manager",
    category: "analytics",
    benefit: "7–11",
    description: 'Hermes Q&A: "What did I prescribe Mrs. J. last month?"',
    route: "/api/admin/cases",
    inputs: ["patient_id"],
    outputs: ["timeline", "summary", "pattern"],
    defaultEnabled: true,
  },
  {
    id: "cohort_analytics",
    name: "Patient Cohort Analytics",
    category: "analytics",
    benefit: 26,
    description: "Outcome rates, remedy timelines, symptom-success correlation",
    route: "/api/admin/cohort",
    inputs: ["remedy"],
    outputs: ["outcomes", "top_followups", "success_correlation"],
    defaultEnabled: false,
  },
  {
    id: "family_constellation",
    name: "Family Constellation",
    category: "analytics",
    benefit: 10,
    description: "Family remedy patterns, cross-generational linking",
    route: "/api/admin/family",
    inputs: ["patient_id"],
    outputs: ["pattern"],
    defaultEnabled: false,
  },
  {
    id: "suppression_tracker",
    name: "Suppression Tracker",
    category: "analytics",
    benefit: 11,
    description: "Suppression history alerts and miasm-tracking tags",
    route: "/api/admin/suppression",
    inputs: ["patient_id"],
    outputs: ["suppressions", "warnings"],
    defaultEnabled: true,
  },
  {
    id: "approval_gate",
    name: "Practitioner Approval Gate",
    category: "safety",
    benefit: 50,
    description: "prescriber_ack safety gate (strict/audit/test modes)",
    route: "/api/admin/approve",
    inputs: ["recommendation"],
    outputs: ["status", "audit_log_id"],
    defaultEnabled: true,
  },
  {
    id: "red_flags",
    name: "Red Flag Detector",
    category: "safety",
    benefit: 51,
    description: "Critical/urgent/advisory symptom detection with referral triggers",
    route: "/api/admin/red-flags",
    inputs: ["symptoms"],
    outputs: ["status", "flags", "referral_recommended"],
    defaultEnabled: true,
  },
  {
    id: "phi_scrubber",
    name: "PHI Scrubber",
    category: "safety",
    benefit: 49,
    description: "Automated PHI detection + reversible pseudonym mapping",
    route: "/api/admin/phi-scrub",
    inputs: ["text"],
    outputs: ["scrubbed", "pseudonyms"],
    defaultEnabled: true,
  },
  {
    id: "audit_trail",
    name: "Audit Trail",
    category: "safety",
    benefit: "32, 53",
    description: "SHA-256 hash chain, immutable prescription logs, licensure export",
    route: "/api/admin/audit",
    inputs: ["record"],
    outputs: ["log_id", "integrity"],
    defaultEnabled: true,
  },
  {
    id: "remedy_relationships",
    name: "Remedy Relationships",
    category: "materia_medica",
    benefit: "4, 19–21",
    description: "Complementary, antidotal, inimical, antidote classical tables",
    route: "/api/admin/relationships",
    inputs: ["remedy"],
    outputs: ["complementary", "antidotes", "inimical"],
    defaultEnabled: true,
  },
  {
    id: "kent_vs_boenn",
    name: "Kent vs Boenninghausen",
    category: "materia_medica",
    benefit: 46,
    description: "Both methods side-by-side, divergence analysis, auto-recommendation",
    route: "/api/admin/kent-vs-boen",
    inputs: ["rubrics"],
    outputs: ["kent", "boenninghausen", "recommendation"],
    defaultEnabled: false,
  },
  {
    id: "personality_bridge",
    name: "Personality Engine Bridge",
    category: "materia_medica",
    benefit: "47, 56",
    description: "Link 50-remedy personality system to OOREP remedy IDs",
    route: "/api/admin/personality",
    inputs: ["remedy"],
    outputs: ["personality_profile"],
    defaultEnabled: false,
  },
  {
    id: "student_training",
    name: "Student Training",
    category: "teaching",
    benefit: 38,
    description: "Simulated patients, 4-option quizzes, progress tracking",
    route: "/api/admin/training",
    inputs: ["mode"],
    outputs: ["simulated_case", "quiz"],
    defaultEnabled: false,
  },
  {
    id: "vignette_quiz",
    name: "Clinical Vignette Quiz",
    category: "teaching",
    benefit: 45,
    description: "Real outcome records → difficulty-tiered teaching quizzes",
    route: "/api/admin/vignette-quiz",
    inputs: ["topic"],
    outputs: ["quiz"],
    defaultEnabled: false,
  },
  {
    id: "grand_rounds",
    name: "Grand Rounds",
    category: "teaching",
    benefit: 48,
    description: "Multi-case synthesis, common themes, markdown teaching narratives",
    route: "/api/admin/grand-rounds",
    inputs: ["patient_ids"],
    outputs: ["narrative", "themes"],
    defaultEnabled: false,
  },
  {
    id: "soap_assembler",
    name: "SOAP Assembler",
    category: "workflow",
    benefit: 31,
    description: "Template-based SOAP generation from case notes",
    route: "/api/admin/soap",
    inputs: ["case_notes"],
    outputs: ["soap"],
    defaultEnabled: false,
  },
  {
    id: "letter_generator",
    name: "Letter Generator",
    category: "workflow",
    benefit: 34,
    description: "Referral / summary / prescription letters with homeopathic rationale",
    route: "/api/admin/letter",
    inputs: ["case_id", "letter_type"],
    outputs: ["letter_md"],
    defaultEnabled: false,
  },
  {
    id: "freshness_tracker",
    name: "Remedy Freshness Tracker",
    category: "workflow",
    benefit: 39,
    description: "Staleness alerts, review queue, proven-source tracking",
    route: "/api/admin/freshness",
    inputs: ["remedy"],
    outputs: ["staleness_score", "review_queue"],
    defaultEnabled: false,
  },
  {
    id: "rubric_gap",
    name: "Rubric Gap Analyzer",
    category: "workflow",
    benefit: 40,
    description: "Coverage gap detection, rubric quality scoring, new-rubric suggestions",
    route: "/api/admin/rubric-gaps",
    inputs: ["symptoms"],
    outputs: ["gaps", "quality_scores"],
    defaultEnabled: false,
  },
  {
    id: "subagent_orchestrator",
    name: "Subagent Orchestrator",
    category: "infrastructure",
    benefit: "35–37",
    description: "Case analysis plans, literature review delegation, second-opinion routing",
    route: "/api/admin/orchestrate",
    inputs: ["task"],
    outputs: ["plan"],
    defaultEnabled: false,
  },
  {
    id: "model_router",
    name: "Model Router",
    category: "infrastructure",
    benefit: 57,
    description: "Local/cloud task routing, performance tracking, fallback chains",
    route: "/api/admin/model-route",
    inputs: ["task"],
    outputs: ["route"],
    defaultEnabled: false,
  },
  {
    id: "materia_medica",
    name: "Materia Medica",
    category: "materia_medica",
    benefit: "18, 21",
    description: "Full-text proving DB for classical materia medica lookup",
    route: "/api/admin/materia-medica",
    inputs: ["remedy"],
    outputs: ["proving_text", "sources"],
    defaultEnabled: false,
  },
  {
    id: "kingdom_taxonomy",
    name: "Kingdom Taxonomy",
    category: "materia_medica",
    benefit: 22,
    description: "Mineral/Plant/Animal tags with family cross-references",
    route: "/api/admin/kingdom",
    inputs: ["remedy"],
    outputs: ["kingdom", "family", "source"],
    defaultEnabled: false,
  },
  {
    id: "botanical_bridge",
    name: "Botanical Bridge",
    category: "materia_medica",
    benefit: 28,
    description: "WHO Monograph cross-map for botanical remedies",
    route: "/api/admin/botanical",
    inputs: ["remedy"],
    outputs: ["monograph", "safety_flags"],
    defaultEnabled: false,
  },
  {
    id: "genomic_hypothesis",
    name: "Genomic Hypothesis",
    category: "materia_medica",
    benefit: 29,
    description: "SNP → remedy outcome correlation hypotheses",
    route: "/api/admin/genomic",
    inputs: ["snp_list"],
    outputs: ["hypotheses", "confidence"],
    defaultEnabled: false,
  },
  {
    id: "flashcard_srs",
    name: "Flashcard SRS",
    category: "teaching",
    benefit: 44,
    description: "SM-2 spaced repetition for materia medica study",
    route: "/api/admin/srs",
    inputs: ["remedy", "user_id"],
    outputs: ["due_cards", "stats"],
    defaultEnabled: false,
  },
  {
    id: "cron_tasks",
    name: "Cron Tasks",
    category: "infrastructure",
    benefit: "33, 42, 43",
    description: "Follow-up alerts, vector auto-rebuild, GitHub backup",
    route: "/api/admin/cron",
    inputs: ["task_name"],
    outputs: ["status"],
    defaultEnabled: false,
  },
];

export async function GET(_request: Request) {
  return NextResponse.json({ ok: true, modules: MODULES });
}
