"""
Letter Generator — Benefit #34

Produces formatted clinical letters:
  1. Referral letters
  2. Patient summaries
  3. Prescription rationale letters

All generated letters are persisted to SQLite so they can be reviewed,
re-printed, or exported later.

Usage:
    from oorep.letter_generator import LetterGenerator
    gen = LetterGenerator()

    referral = gen.generate_referral(
        patient_info={"pseudonym": "PT-001", "age": "45", "gender": "F"},
        red_flags=["Chest pain on exertion"],
        rationale="Ruled out cardiac etiology; recommend ECG",
        provider_info={"name": "Dr. Smith", "specialty": "Cardiology"},
    )
"""

import json
import sqlite3
import uuid
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

try:
    from scripts.remedy_feedback import DATA_DIR as FB_DATA_DIR
    DEFAULT_DB = FB_DATA_DIR / "feedback.db"
except Exception:
    DEFAULT_DB = Path(__file__).resolve().parent.parent / "data" / "feedback.db"


# ── Shared letter templates ─────────────────────────────────────────────────
_HEADER_TEMPLATE = """{divider}
{title}
{divider}
Date: {date}
Generated by: OOREP Local Repertory System
Classification: {classification}
{divider}
"""

_FOOTER_TEMPLATE = """
{divider}
This letter was generated by the OOREP homeopathic clinical support system.
It does not replace professional clinical judgment.
{divider}
"""


class LetterGenerator:
    """
    Generate and archive clinical correspondence.

    Letters are stored in ``generated_letters`` (SQLite) with:
      - ``id``
      - ``type`` (referral | patient_summary | prescription_rationale)
      - ``patient`` (pseudonym or descriptor)
      - ``content`` (full formatted text)
      - ``created_at``
    """

    def __init__(self, db_path: Optional[Path] = None):
        """
        Args:
            db_path: SQLite database path. Defaults to project feedback.db.
        """
        if db_path is None:
            self.db_path = Path(DEFAULT_DB)
        else:
            self.db_path = Path(db_path)
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._init_db()

    def _init_db(self) -> None:
        """Create the ``generated_letters`` table if missing."""
        conn = sqlite3.connect(str(self.db_path))
        cursor = conn.cursor()
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS generated_letters (
                id TEXT PRIMARY KEY,
                type TEXT NOT NULL,
                patient TEXT,
                content TEXT NOT NULL,
                created_at TEXT DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        conn.commit()
        conn.close()

    # ── Core formatting helpers ─────────────────────────────────────────────

    @staticmethod
    def _format_header(title: str, classification: str = "CONFIDENTIAL") -> str:
        divider = "=" * 60
        return _HEADER_TEMPLATE.format(
            divider=divider,
            title=title.upper(),
            date=datetime.now().strftime("%Y-%m-%d %H:%M"),
            classification=classification,
        )

    @staticmethod
    def _format_footer() -> str:
        divider = "=" * 60
        return _FOOTER_TEMPLATE.format(divider=divider)

    def _persist(self, letter_id: str, letter_type: str, patient: str, content: str) -> None:
        """Insert a letter record into SQLite."""
        conn = sqlite3.connect(str(self.db_path))
        cursor = conn.cursor()
        cursor.execute(
            "INSERT INTO generated_letters (id, type, patient, content, created_at) VALUES (?, ?, ?, ?, ?)",
            (letter_id, letter_type, patient, content, datetime.now().isoformat()),
        )
        conn.commit()
        conn.close()

    # ── 1. Referral letter ────────────────────────────────────────────────────

    def generate_referral(
        self,
        patient_info: Dict[str, str],
        red_flags: List[str],
        rationale: str,
        provider_info: Dict[str, str],
    ) -> str:
        """
        Generate a referral letter to an external provider.

        Args:
            patient_info: Dict with keys such as ``pseudonym``, ``age``,
                          ``gender``, or free-form text under ``summary``.
            red_flags: List of red-flag findings prompting the referral.
            rationale: Clinical reasoning for the referral.
            provider_info: Dict with ``name``, ``specialty``, and optionally
                           ``address`` or ``contact``.

        Returns:
            Formatted letter text (and persisted to DB).
        """
        patient_str = patient_info.get("pseudonym") or patient_info.get("summary", "Unknown")
        header = self._format_header("Referral Letter")
        body_lines = [
            f"To: {provider_info.get('name', 'Unknown Provider')}",
            f"Specialty: {provider_info.get('specialty', 'N/A')}",
            f"Contact: {provider_info.get('contact', 'N/A')}",
            "",
            f"Re: Patient {patient_str}",
            f"  Age / Gender: {patient_info.get('age', 'N/A')} / {patient_info.get('gender', 'N/A')}",
            "",
            "URGENT RED FLAGS:",
        ]
        for flag in red_flags:
            body_lines.append(f"  • {flag}")
        body_lines.extend([
            "",
            "CLINICAL RATIONALE:",
            rationale,
            "",
            "REQUEST:",
            "Please evaluate the above and provide recommendations "
            "for integrated management. We remain the primary homeopathic provider.",
            "",
            "Regards,",
            "  [Practitioner signature placeholder]",
        ])
        body = "\n".join(body_lines)
        letter = f"{header}\n{body}\n{self._format_footer()}"

        letter_id = str(uuid.uuid4())[:12]
        self._persist(letter_id, "referral", patient_str, letter)
        return letter

    # ── 2. Patient summary ────────────────────────────────────────────────────

    def generate_patient_summary(
        self,
        patient_info: Dict[str, str],
        remedies: List[Dict[str, Any]],
        timeline: List[Dict[str, Any]],
    ) -> str:
        """
        Generate a patient-friendly summary of their case and treatment.

        Args:
            patient_info: Dict with ``pseudonym``, ``age``, ``summary``, etc.
            remedies: List of remedy dicts, each with ``name``, ``potency``,
                      ``date``, ``status``.
            timeline: List of event dicts with ``date`` and ``description``.

        Returns:
            Formatted summary text (and persisted to DB).
        """
        patient_str = patient_info.get("pseudonym") or patient_info.get("summary", "Unknown")
        header = self._format_header("Patient Summary", classification="PATIENT COPY")
        body_lines = [
            f"Dear {patient_info.get('salutation', 'Patient')},",
            "",
            "Below is a summary of your homeopathic care record:",
            "",
            "PERSONAL DETAILS:",
            f"  Pseudonym:     {patient_str}",
            f"  Age / Gender:  {patient_info.get('age', 'N/A')} / {patient_info.get('gender', 'N/A')}",
            "",
            "REMEDIES PRESCRIBED:",
        ]
        for rem in remedies:
            body_lines.append(
                f"  • {rem.get('name', 'Unknown')} {rem.get('potency', '')}  "
                f"({rem.get('date', 'N/A')}) — {rem.get('status', 'active')}"
            )
        body_lines.extend([
            "",
            "CARE TIMELINE:",
        ])
        for event in timeline:
            body_lines.append(f"  {event.get('date', 'N/A')}: {event.get('description', '')}")
        body_lines.extend([
            "",
            "If you have questions, please contact your practitioner.",
            "",
            "Kind regards,",
            "  Your Care Team",
        ])
        body = "\n".join(body_lines)
        letter = f"{header}\n{body}\n{self._format_footer()}"

        letter_id = str(uuid.uuid4())[:12]
        self._persist(letter_id, "patient_summary", patient_str, letter)
        return letter

    # ── 3. Prescription rationale ─────────────────────────────────────────────

    def generate_prescription_rationale(
        self,
        patient_info: Dict[str, str],
        remedy: str,
        rubrics: List[Dict[str, Any]],
        potency: str,
    ) -> str:
        """
        Generate a detailed prescription rationale letter for legal / audit
        or informed-consent documentation.

        Args:
            patient_info: Dict with patient pseudonym and demographics.
            remedy: Remedy name or abbreviation (e.g. "Pulsatilla" or "Puls.").
            rubrics: List of rubric dicts with ``fullpath``, ``source``,
                     ``grade`` or ``weight``.
            potency: Prescribed potency string (e.g. "30C").

        Returns:
            Formatted rationale text (and persisted to DB).
        """
        patient_str = patient_info.get("pseudonym") or patient_info.get("summary", "Unknown")
        header = self._format_header("Prescription Rationale")
        body_lines = [
            f"Patient: {patient_str}",
            f"Date: {datetime.now().strftime('%Y-%m-%d')}",
            "",
            "PRESCRIBED REMEDY:",
            f"  {remedy} {potency}",
            "",
            "REPERTORIZATION BASIS:",
            "The following rubrics were selected from the OOREP repertory "
            "based on the patient's expressed symptoms and clinical findings:",
            "",
        ]
        for r in rubrics:
            body_lines.append(
                f"  • {r.get('fullpath', 'Unknown rubric')}  "
                f"[source: {r.get('source', '?')}, grade: {r.get('weight', r.get('grade', '?'))}]"
            )
        body_lines.extend([
            "",
            "RATIONALE:",
            f"{remedy} emerged as the leading remedy after classical grade-sum "
            f"repertorization across the symptom totality described above. "
            f"The potency ({potency}) was selected according to classical guidelines "
            f"for the identified symptom layer and chronicity.",
            "",
            "The practitioner has reviewed this prescription and acknowledges "
            "clinical responsibility for the treatment plan.",
            "",
            "Signed: _________________________",
            "Date:   _________________________",
        ])
        body = "\n".join(body_lines)
        letter = f"{header}\n{body}\n{self._format_footer()}"

        letter_id = str(uuid.uuid4())[:12]
        self._persist(letter_id, "prescription_rationale", patient_str, letter)
        return letter

    # ── Retrieval API ───────────────────────────────────────────────────────

    def get_letter(self, letter_id: str) -> Optional[Dict[str, Any]]:
        """Retrieve a generated letter by its ID."""
        conn = sqlite3.connect(str(self.db_path))
        cursor = conn.cursor()
        cursor.execute(
            "SELECT id, type, patient, content, created_at FROM generated_letters WHERE id = ?",
            (letter_id,),
        )
        row = cursor.fetchone()
        conn.close()
        if not row:
            return None
        return {
            "id": row[0],
            "type": row[1],
            "patient": row[2],
            "content": row[3],
            "created_at": row[4],
        }

    def list_letters(
        self,
        letter_type: Optional[str] = None,
        patient: Optional[str] = None,
        limit: int = 100,
    ) -> List[Dict[str, Any]]:
        """
        List archived letters, optionally filtered by type or patient.
        Ordered newest-first.
        """
        conn = sqlite3.connect(str(self.db_path))
        cursor = conn.cursor()
        sql = (
            "SELECT id, type, patient, content, created_at FROM generated_letters WHERE 1=1"
        )
        params: List[Any] = []
        if letter_type:
            sql += " AND type = ?"
            params.append(letter_type)
        if patient:
            sql += " AND patient = ?"
            params.append(patient)
        sql += " ORDER BY created_at DESC LIMIT ?"
        params.append(limit)
        cursor.execute(sql, params)
        rows = cursor.fetchall()
        conn.close()
        return [
            {
                "id": r[0],
                "type": r[1],
                "patient": r[2],
                "content": r[3],
                "created_at": r[4],
            }
            for r in rows
        ]
