#!/usr/bin/env python3
"""
Generic Scaffold Builder — generates placeholder module + tests for features
without dedicated builder scripts. This enables autonomous overnight builds
for all features even if a specific builder hasn't been written yet.

The scaffold creates:
  - oorep/{slug}.py with class skeleton, docstring, and TODO stubs
  - tests/test_{slug}.py with basic construction and smoke tests

A future LLM session can flesh out the implementation from the scaffold.
"""

import json
import sys
from pathlib import Path

PROJECT = Path("/home/walker/projects/oorep-local-repertory")
QUEUE_FILE = PROJECT / "scripts" / "overnight_build_queue.json"


def generate_module(feature: dict) -> str:
    slug = feature["slug"]
    name = feature["name"]
    feature_id = feature["id"]
    desc = feature["description"]
    deps = feature.get("dependencies", [])

    imports = "from typing import Dict, List, Optional, Any\n"
    for dep in deps:
        if dep.endswith(".py"):
            mod_name = dep.replace(".py", "").replace("/", ".")
            imports += f"# from oorep.{mod_name} import ...\n"

    code = f'''"""
{name} — Feature #{feature_id}

{desc}

Usage:
    from oorep.{slug} import {slug.replace("_", " ").title().replace(" ", "")}
    engine = {slug.replace("_", " ").title().replace(" ", "")}(repertory)
    result = engine.process(...)

TODO: Implement core logic. This is an autogenerated scaffold.
"""

{imports}


class {slug.replace("_", " ").title().replace(" ", "")}:
    """
    {name} engine.
    """

    def __init__(self, repertory: Optional[Any] = None):
        self.rep = repertory

    def process(self, **kwargs) -> Dict[str, Any]:
        """
        Main entry point. Override with actual implementation.
        """
        return {{"status": "stub", "feature_id": {feature_id}, "feature_name": "{name}"}}
'''
    return code


def generate_tests(feature: dict) -> str:
    slug = feature["slug"]
    name = feature["name"]
    feature_id = feature["id"]
    class_name = slug.replace("_", " ").title().replace(" ", "")

    code = f'''"""
Tests for {name} (Feature #{feature_id})
"""

import pytest
from oorep.{slug} import {class_name}


class Test{class_name}:

    def test_construction(self):
        engine = {class_name}()
        assert engine is not None

    def test_process_returns_dict(self):
        engine = {class_name}()
        result = engine.process()
        assert isinstance(result, dict)
        assert result["status"] == "stub"
        assert result["feature_id"] == {feature_id}

    def test_process_with_mock_repertory(self):
        class MockRep:
            pass
        engine = {class_name}(MockRep())
        assert engine.rep is not None
'''
    return code


def write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"[WROTE] {path}")


def build_feature(slug: str) -> bool:
    queue = json.loads(QUEUE_FILE.read_text())
    feature = next((f for f in queue["features"] if f["slug"] == slug), None)
    if not feature:
        print(f"[ERROR] Feature '{slug}' not found in queue")
        return False

    print(f"[SCAFFOLD] Feature #{feature['id']}: {feature['name']} ({slug})")

    # Write module
    module_path = PROJECT / "oorep" / f"{slug}.py"
    write_file(module_path, generate_module(feature))

    # Write tests
    test_path = PROJECT / "tests" / f"test_{slug}.py"
    write_file(test_path, generate_tests(feature))

    print(f"[DONE] Scaffold for Feature #{feature['id']} written")
    return True


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("slug", help="Feature slug to scaffold")
    args = parser.parse_args()
    ok = build_feature(args.slug)
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    import argparse
    main()
